Change JPEG -> SVG
w3c/rdf-semantics pull request #43
Opened 2023-09-10 18:26 UTC by domel

- Change JPEG (raster image) to SVG (vector image). 
- Remove `example6.jpg` that wasn't used in HTML

See https://github.com/w3c/rdf-semantics/issues/42

2023-09-10 19:17 UTC, gkellogg reviewed
If the SVG files have editable references, it would be good to put comments in place pointing to them, in case anything needs to be changed in the future.

2023-09-10 19:22 UTC, domel commented
> If the SVG files have editable references, it would be good to put comments in place pointing to them, in case anything needs to be changed in the future.

@gkellogg What do you mean by "editable references"? Do you want to add (XML) comments in SVG files?

2023-09-10 19:34 UTC, domel commented
BTW, here is a [Preview](https://raw.githack.com/w3c/rdf-semantics/svg_pictures/spec/index.html).

2023-09-10 19:51 UTC, gkellogg commented
If you look at https://github.com/w3c/rdf-semantics/issues/42#issuecomment-1712579511 you’ll see an inline XML-style comment “Source for this image may be found …” in the code snippet. That’s what I was referring to.

2023-09-10 20:20 UTC, domel commented
@gkellogg Oh yes. I didn't add it on purpose. Experienced by other PRs and @pfps comments, I preferred not to change to much the HTML structure. If there is consent to this change, I will be happy to add `<figure>`, even in the last image, it is worth adding `<picture>`.

2023-09-10 21:11 UTC, gkellogg commented
There are some accessibility requirements for figures, but I think they mostly describe more explicit RDF statements. `alt`, and `aria-describedby` attributes are probably appropriate, but they don't necessarily need to be wrapped in a figure.

My point was that, in the case of RDF Concepts, [figure 2](https://www.w3.org/TR/rdf12-concepts/#fig-quoted-triple) includes the following comment:

```
<!-- Source for this file is at https://docs.google.com/drawings/d/1I_QxbUgnQXumXzb8c0WNJHIQ-mtRs2S80dDG6i9aOD8 -->
```

This allows someone to go to that URL and re-edit the figure to be able to export an update SVG if it ever becomes necessary. This can be put anywhere near the image.

2023-09-10 21:18 UTC, domel commented
But I did the pictures locally in my computer so I guess that it can only link to the github repo.

2023-09-10 21:55 UTC, gkellogg commented
If you did the pictures locally using some format other than SVG, it might be worth adding the source for these drawings to the repository with some README that indicated any software used to process them. Of course, if you created them by hand, then they can probably be edited by hand in the future.

2023-09-10 22:57 UTC, domel commented
Yes, I created them by hand. I used the well-known Inkscape.

2023-09-11 01:36 UTC, gkellogg commented
Cool, I think putting something about how the images are authored in a README would be useful. Trying to edit them by hand would be beyond me.

2023-09-11 13:04 UTC, domel commented
@gkellogg Done

2023-09-11 13:59 UTC, gkellogg approved these changes

2023-09-11 14:49 UTC, TallTed requested changes
Small tweaks for `example5.svg`. Otherwise, these look just right!

2023-09-11 14:49 UTC, TallTed commented on spec/RDF12SemanticsDiagrams/example5.svg
The connecting lines/arrows should not be composed of two parts; they should each be a single line with the `ex:hasChild` label atop, as in `example3.svg`. As these are, it looks like `ex:Alice` and `ex:Bob` each point to their neighboring `ex:hasChild`, and that the two `ex:hasChild` each point to the central (blank) ellipse.

2023-09-11 19:47 UTC, domel commented on spec/RDF12SemanticsDiagrams/example5.svg
done

2023-09-13 15:12 UTC, TallTed approved these changes

2023-09-22 20:20 UTC, merged