Complete entailment algorithm in Semantics Appendix
w3c/rdf-semantics pull request #48
Opened 2024-04-24 11:56 UTC by Antoine-Zimmermann

This covers the case of every graph entails `?s rdf:type rdfs:Resource`.

2024-04-24 19:21 UTC, TallTed requested changes
randomly noticed punctuation fixes

2024-04-24 19:21 UTC, TallTed commented on spec/index.html
>      <li>Determine if E has an instance which is a subset of the set, i.e. whether the enlarged set <a>simply entails</a> E.</li>
```suggestion
    <li>Determine if E has an instance which is a subset of the set, i.e., whether the enlarged set <a>simply entails</a> E.</li>
```

2024-04-24 19:21 UTC, TallTed commented on spec/index.html
>      <li>If no triples were added in step 2., add the RDF (and RDFS) axiomatic triples which contain <code>rdf:_1</code>.</li>
```suggestion
    <li>If no triples were added in step 2, add the RDF (and RDFS) axiomatic triples which contain <code>rdf:_1</code>.</li>
```

2024-05-02 14:30 UTC, pfps commented
I tried to commit Ted's fixes, but now I can't see the entire PR.   Has something gone wrong?

2024-05-02 16:54 UTC, TallTed approved these changes

2024-05-23 16:06 UTC, pfps approved these changes
Looks OK

2024-06-27 16:41 UTC, doerthe approved these changes

2024-06-27 16:54 UTC, merged