Recognize rdf:dirLangString
w3c/rdf-semantics pull request #60
Opened 2024-12-12 11:16 UTC by afs

See #59.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-semantics/pull/60.html" title="Last updated on Dec 20, 2024, 9:46 AM UTC (3be347c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-semantics/60/a9d9890...3be347c.html" title="Last updated on Dec 20, 2024, 9:46 AM UTC (3be347c)">Diff</a>

2024-12-12 11:28 UTC, afs commented on spec/index.html
> +        <a data-cite="XMLSCHEMA11-2#string"><code>xsd:string</code></a>,
Reordered to put the more common datatype first.

2024-12-12 17:30 UTC, pfps requested changes
Needs a discussion of whether Concepts needs to be changed.

2024-12-12 21:33 UTC, afs commented
> Needs a discussion of whether Concepts needs to be changed.

What change might be necessary?

2024-12-13 07:21 UTC, pfps commented
Concepts doesn't say that any datatype is REQUIRED, which seems to me to be needed if Semantics says that RDF reasoning REQUIRES some datatypes.

2024-12-13 08:21 UTC, afs commented
This PR is not about the general issue. 

RDF Semantics does require `xsd:string`, `rdf:langString`, therefore it should require `rdf:dirLangString`. This should have been down when the WG completed changes for base direction. It got missed and this PR ensures it does not get lost.

The wider issue is elsewhere:
https://github.com/w3c/rdf-concepts/issues/60#issuecomment-2538919568

2024-12-13 08:30 UTC, pfps commented
I created https://github.com/w3c/rdf-concepts/issues/122 explicitly about whether Concepts should discuss requirements for RDF entailment.

2024-12-13 08:30 UTC, pfps approved these changes

2024-12-13 20:16 UTC, TallTed approved these changes

2024-12-19 18:36 UTC, pchampin commented
@afs after reverting #52 per [our resolution today](https://www.w3.org/2024/12/19-rdf-star-minutes.html#4761), I tried to rebased this PR, but the formatting change created a conflict :-/ . I will work on it a little later.

2024-12-19 21:42 UTC, pchampin commented
> @afs after reverting #52 per [our resolution today](https://www.w3.org/2024/12/19-rdf-star-minutes.html#4761), I tried to rebased this PR, but the formatting change created a conflict :-/ . I will work on it a little later.

that's now fixed. This PR is rebased on the new main (i.e. after #52 has been reverted)

2024-12-19 21:43 UTC, gkellogg commented
> @afs after reverting #52 per [our resolution today](https://www.w3.org/2024/12/19-rdf-star-minutes.html#4761), I tried to rebased this PR, but the formatting change created a conflict :-/ . I will work on it a little later.

If there are no intervening commits to preserve, it might be easier to just reset the head and force-push to eliminate those commits.

2024-12-20 09:48 UTC, afs commented
Rebased to current main, preview and diff rebuilt.

Editors - this is ready to merge.

2024-12-20 15:41 UTC, gkellogg approved these changes

2024-12-21 15:15 UTC, afs commented
Closing.
There are more areas that need updating for `rdf:dirLangString`.

2024-12-21 15:15 UTC, closed without merging