Recognize rdf:dirLangString
w3c/rdf-semantics pull request #64
Opened 2024-12-21 15:23 UTC by afs

Replacement for #60.

This PR includes updates for the "Semantic conditions for literals table".

2024-12-21 16:07 UTC, gkellogg approved these changes
On tiny grammar change. Otherwise, looks good.

2024-12-21 16:07 UTC, gkellogg commented on spec/index.html
> +    are classified as a datatype IRIs and interpreted to denote a datatype,
```suggestion
    are classified as datatype IRIs and interpreted to denote a datatype,
```

2024-12-21 22:14 UTC, gkellogg approved these changes

2024-12-21 22:38 UTC, pfps requested changes
I believe that there needs to be a WG decision to add this.  I created https://github.com/w3c/rdf-star-wg/issues/139 for this purpose.

(The request changes flag is only to prevent yet another rogue merge.)

2024-12-22 09:04 UTC, afs commented
> I believe that there needs to be a WG decision to add this.

There has been this [WG resolution](https://www.w3.org/2024/09/24-rdf-star-minutes.html#d0a5)
> support initial text direction in RDF Language-Tagged Literals

and this [WG resolution](https://www.w3.org/2023/09/28-rdf-star-minutes#r03)
> Add base direction as a forth element of Literals

and this [WG resolution](https://www.w3.org/2023/05/11-rdf-star-minutes.html#r02)
> Accept RDF-Concepts issue "text direction"
---

RDF 1.1 Semantics has it's own description of datatypes - it needs updating.

RDF 1.1 Semantics calls out `rdf:langString` as a normative "exception" because it has a special value mapping from RDF term to value.  It gives a fixed (normative) mechanism for `rdf:langString` that includes handling the language tag in a case insensitive manner. Semantic extensions must agree on this exception. 

RDF 1.2 Semantics must do so for `rdf:dirLangString` with a compatible mechanism, adding dealing with base direction. This PR uses exact the same text wording style to emphasis this.

The same is true for `rdf:dirLangString` in order to enact the WG resolutions, making it available for semantic extensions with the same interpretation for all semantic extensions.

Otherwise the text of RDF Semantics need significant revision because it talks in general about the datatype mapping lexical space to value space.

2024-12-22 12:28 UTC, pfps commented
Part of this PR is
> RDF processors are not required to <a>recognize</a> any datatype IRIs other than
    <a data-cite="XMLSCHEMA11-2#string"><code>xsd:string</code></a>,
    <a data-cite="RDF12-CONCEPTS#dfn-language-tagged-string"><code>rdf:langString</code></a>, and
    <a data-cite="RDF12-CONCEPTS#dfn-dir-lang-string"><code>rdf:dirLangString</code></a>
I don't believe that the requirement to recognize directional language strings has been decided.

2024-12-22 12:47 UTC, afs commented
Why is `rdf:langString` required?

2024-12-22 19:30 UTC, gkellogg commented
I believe the need to support `rdf:dirLangString` semantics is implicit in the other approvals. Indeed, if it were not a recognized datatype with conditions based on `rdf:langString` it would be inconsistent. The Working Group's time is quite limited, and easily gets taken up on perm-threads. No need to add further burden to go over something that is so clearly necessary. If there are reasonable objections, they can be made here, or in #60.

2025-01-10 19:23 UTC, TallTed requested changes

2025-01-10 19:23 UTC, TallTed commented on spec/index.html
>      are <a>recognized</a>, they MUST be interpreted as described there, and when the IRI <code>rdf:PlainLiteral</code> is <a>recognized</a>, it MUST be interpreted to denote the datatype defined in [
```suggestion
    <em>are</em> <a>recognized</a>, they MUST be interpreted as described there, and
    when the IRI <code>rdf:PlainLiteral</code> is <a>recognized</a>,
    it MUST be interpreted to denote the datatype defined in [[!RDF-PLAIN-LITERAL]].
    RDF processors MAY recognize other datatype IRIs,
    but when other datatype IRIs are <a>recognized</a>,
    the mapping between the datatype IRI and the datatype it <a>denotes</a>
    MUST be specified unambiguously,
    and MUST be fixed during all RDF transformations or manipulations.
    In practice, this can be achieved by the IRI linking
    to an external specification of the datatype
    which describes both the components of the datatype itself
    and the fact that the IRI identifies the datatype,
    thereby fixing a value of the <a>datatype map</a> of this IRI.</p>
```

2025-01-10 19:23 UTC, TallTed commented on spec/index.html
> +    The semantics of literals with these as their datatype are given below.
```suggestion
    The semantics of literals with either of these as their datatype are given below.
```

2025-01-10 19:23 UTC, TallTed commented on spec/index.html
> +    where D includes <code>rdf:langString</code>, <code>rdf:dirLangString</code> and <code>xsd:string</code>, and which satisfies:</p>
```suggestion
    where D includes <code>rdf:langString</code>, <code>rdf:dirLangString</code>, and <code>xsd:string</code>, and which satisfies:</p>
```

2025-01-10 19:23 UTC, TallTed commented on spec/index.html
> +    are defined in [[!RDF12-CONCEPTS]].
```suggestion
  <p>Three other datatypes &mdash; <a data-cite="RDF12-CONCEPTS#section-XMLLiteral"><code>rdf:XMLLiteral</code></a>,
    <a data-cite="RDF12-CONCEPTS#section-html"><code>rdf:HTML</code></a>, and
    <a data-cite="RDF12-CONCEPTS#section-json"><code>rdf:JSON</code></a> &mdash;
    are defined in [[!RDF12-CONCEPTS]].
```

2025-01-10 19:23 UTC, TallTed commented on spec/index.html
> +        <p>ICEXT(I(<code>rdf:dirLangString</code>)) is the set {I(E) : E a directional language-tagged string }</p>
A decision to be made: whether `{}` wrappers that permit it should *always* or *never* be internally space padded; that is whether `{` should always or never be followed, *and* `}` should always or never be preceded, by a space ` `. I am *strongly* in favor of _always_ including such space characters, as I have never found them to decrease comprehension, and very often to increase it.

I find that *sometimes* including such padding, as here on the closing `string }` but not on the opening `{I(E)`, significantly decreases comprehension, especially by readers who are not yet familiar with the overall subject matter.

(A similar question applies to `<>``, ()`, `[]`, and any other similar wrapping punctuation.)
```suggestion
        <p>ICEXT(I(<code>rdf:dirLangString</code>)) is the set { I(E) : E a directional language-tagged string }</p>
```

2025-01-16 21:35 UTC, afs commented on spec/index.html
> +        <p>ICEXT(I(<code>rdf:dirLangString</code>)) is the set {I(E) : E a directional language-tagged string }</p>
Maybe; but this PR is not the place. It should be a separate PR so we can see the overall effect.

2025-01-16 21:40 UTC, afs commented on spec/index.html
> +    which have two syntactic components, a string and a language tag; and
It really is a non-Oxford comma subclause!

colon seems to move the natural break away from the semi-colon; and is a different form to the next sentence.

2025-01-22 17:16 UTC, TallTed commented on spec/index.html
> +    which have two syntactic components, a string and a language tag; and
@afs -- Perhaps this?
```suggestion
    which have two syntactic components — a string and a language tag — and
```

2025-01-22 17:19 UTC, TallTed commented on spec/index.html
> +    which have three syntactic components, a string, a language tag, and a base direction.
I am not convinced that the comma following `components` is a correct construction. 

Even if it is correct English, I believe it will be confusing to non-native English readers.

I would be OK using an emdash instead of the colon.
```suggestion
    which have three syntactic components — a string, a language tag, and a base direction.
```

2025-01-22 17:29 UTC, TallTed commented on spec/index.html
> +        <p>ICEXT(I(<code>rdf:dirLangString</code>)) is the set {I(E) : E a directional language-tagged string }</p>
Raised as https://github.com/w3c/rdf-star-wg/issues/143

2025-01-22 17:47 UTC, pfps commented
> > Why is rdf:langString required?
> 
> No answer has been forthcoming.
> 
> I believe that because `rdf:langString` is required then `rdf:dirLangString` is required because it has everything special about the value space that `rdf:langString` has.
> 
> Therefore this can go into the doc - if there are issues (1) state what they are (2) add an editors note.

rdf:langString is historical.

2025-01-22 18:18 UTC, TallTed commented
I want to make sure that discussion continues on my suggestions which are marked "resolved" above, but which were not applied and which I cannot now mark "unresolved":
1. https://github.com/w3c/rdf-semantics/pull/64#discussion_r1925693638
2. https://github.com/w3c/rdf-semantics/pull/64#discussion_r1925689437

2025-01-22 18:38 UTC, afs commented
> rdf:langString is historical.

What evidence do you have for that?

`rdf:langString` was introduced in RDF 1.1 and it continues in 1.2. It has been part of the discussions around literals with base direction which the WG has resolved to accept.

Do not confuse it with `rdf:PlainLiteral`
BiDirection text is not in-scope.

2025-01-22 19:03 UTC, pfps commented
From RDF 1.1 Semantics

> The datatype IRIs rdf:langString and xsd:string MUST be recognized by all RDF interpretations.


> An RDF interpretation recognizing D is a D-interpretation I where D includes rdf:langString and xsd:string, and which satisfies:


So the requirement to recognize rdf:langString is historical.  No WG decision has been made to add rdf:dirlangString here.

2025-01-22 19:15 UTC, afs commented
> There has been this [WG resolution](https://www.w3.org/2024/09/24-rdf-star-minutes.html#d0a5)
>> "support initial text direction in RDF Language-Tagged Literals."

RDF Semantics does not currently support initial text direction (now "base direction").

2025-01-22 19:17 UTC, pfps commented
I do not view that resolution as requiring that the datatype be part of RDF semantics.  It could just as easily be an optional datatype, like rdf:JSON.

2025-01-22 20:12 UTC, afs commented
`rdf:dirLangString` is part of the RDF data model.

"""
A literal in an RDF graph consists of two, three, or four elements, as follow:"
...
if and only if the [datatype IRI](https://www.w3.org/TR/rdf12-concepts/#dfn-datatype-iri) is http://www.w3.org/1999/02/22-rdf-syntax-ns#dirLangString,... a base direction that MUST be either ltr or rtl.
"""

However for `rdf:JSON`::
"""
This section defines additional [datatypes](https://www.w3.org/TR/rdf12-concepts/#dfn-datatype) that RDF implementations MAY support.
"""

2025-01-22 20:57 UTC, pfps commented
The first part is some weak indication that directional strings should be recognized in RDF entailment, but I don't view it as conclusive.  The second part is new in 1.2 and I don't believe that it has any bearing here.

I think all that is required is a quick WG vote as to whether directional strings should be part of RDF entailment.

2025-01-23 18:01 UTC, afs commented on spec/index.html
> +    which have three syntactic components, a string, a language tag, and a base direction.
IMO dashes are not non-native English reader friendly.
I tried to follow the style of the document.
Please take style matters up with the document editors.

2025-01-27 18:31 UTC, TallTed commented on spec/index.html
> +    which have three syntactic components, a string, a language tag, and a base direction.
These can *easily* be read as listing a total of *four or six* things -- 2 syntactic components *plus* 1 string and 1 language tag; or 3 syntactic components *plus* 1 string, 1 language tag, and 1 base direction. I think too much is being asked of a single, very long sentence. Here I break it into two sentences. It could be broken into three or even four.
```suggestion
    In summary: with two exceptions, RDF literals combine a string and an IRI <a data-lt="identify">identifying</a> a datatype.
    The exceptions are <a data-cite="RDF12-CONCEPTS#dfn-language-tagged-string">language-tagged strings</a>,
    which are assigned the type <code>rdf:langString</code>, and
    <a data-cite="RDF12-CONCEPTS#dfn-directional-language-tagged string">directional language-tagged strings</a>,
    which are assigned the type <code>rdf:dirLangString</code>.
    <a data-cite="RDF12-CONCEPTS#dfn-language-tagged-string">language-tagged strings</a>
    have two syntactic components, these being a string and a language tag;
    <a data-cite="RDF12-CONCEPTS#dfn-directional-language-tagged string">directional language-tagged strings</a>
    have three syntactic components, these being a string, a language tag, and a base direction.
```

2025-01-31 16:12 UTC, afs commented on spec/index.html
> +    which have three syntactic components, a string, a language tag, and a base direction.
This is stylistic. I will leave it to the editors of this document.

2025-02-06 17:29 UTC, pfps approved these changes

2025-02-06 17:57 UTC, merged

2025-02-06 20:07 UTC, TallTed commented on spec/index.html
> +    which have three syntactic components, a string, a language tag, and a base direction.
Picked up in https://github.com/w3c/rdf-semantics/issues/83